networks:
  otel-network:
    driver: bridge

services:
  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: jaeger
    environment:
      - OTEL_TRACES_SAMPLER=always_off
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - otel-network
    ports:
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "9411:9411"
    command: ["--collector.zipkin.host-port=:9411", "--log-level=debug"]

  otel-collector:
    build: ./docker/otel-collector/
    container_name: otel-collector
    # image: otel/opentelemetry-collector-contrib:0.119.0
    volumes:
    - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - otel-network
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    depends_on:
      - jaeger

  budger-tracker-api-v2:
    build: ./
    container_name: budger-tracker-api-v2
    environment:
      MONGODB_HOST: "mongodb+srv://budget-tracker.gj4ww.mongodb.net/"
      MONGODB_USER: "vsantos"
      MONGODB_PASS: "R4hv10DP1HN6Iv2H"
    networks:
      - otel-network
    depends_on:
      - otel-collector
    ports:
      - "8080:8080"
