apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
data:
  host: bW9uZ29kYitzcnY6Ly9tb25nb2RiLWF0bGFzLWV4YW1wbGUubW9uZ29kYi5uZXQv # base64 encoded "mongodb+srv://mongodb-atlas-example.mongodb.net/"
  username: cm9vdA== # base64 encoded "admin"
  password: ZXhhbXBsZQ== # base64 encoded "example"
