apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: {{ .Values.namespace.name | default "default" }}
type: Opaque
data:
  host: bW9uZ29kYjovL2xvY2FsLWRldi1tb25nb2RiLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcv # base64 encoded "mongodb://local-dev-mongodb.default.svc.cluster.local:27017/"
  username: cm9vdA== # base64 encoded "root"
  password: cm9vdA== # base64 encoded "root"
