site_name: Budget Tracker API V2
repo_url: https://github.com/vsantos/budget-tracker-api-v2/
plugins:
  - offline
  - swagger-ui-tag
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    - content.tabs.link
    - navigation.footer
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
nav:
  - Home:
    - Welcome:  index.md
    - Concepts: concepts.md
    - Architecture: architecture.md
  - Swagger:  swagger.md
  - API:
    - Internal:
      - http:
        - Controller: api/packages/controller.md
        - Middleware: api/packages/middleware.md
        - Router: api/packages/router.md
      - Model: api/packages/model.md
      - Repository:
        - Repository: api/packages/repository.md
        - MongoDB: api/packages/mongodb.md
      - Observability: api/packages/observability.md
      - Utils:
        - Crypt: api/packages/crypt.md
  - Local Development: local_development.md
  - Contributing: contributing.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vs4ntos/
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.