name: Documentation Deployment

on:
  push:
    tags:
    - '*'
    branches: [feat/*, docs/*, fix/*, break/*]
  pull_request:
    branches: [main, feat/*, docs/*, fix/*, break/*]

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocs-swagger-ui-tag mkdocs-glightbox markdown-include mkdocs-macros-plugin mike

      - name: Deploy to GitHub Pages
        # run: mkdocs gh-deploy --force -f docs/mkdocs.yml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          set +e
          VERSION=$(git describe --tags --abbrev=0)
          VERSION_STATUS_CODE=$?
          set -e

          set -x
          if [[ $VERSION_STATUS_CODE == 128 ]]; then
            VERSION=$(git describe --tags --abbrev=0 --always | cut -c1-10)
            mike deploy --push --update-aliases $version development --config-file=docs/mkdocs.yml
            mike set-default --push development --config-file=docs/mkdocs.yml
          else
            mike deploy --push --update-aliases $VERSION latest --config-file=docs/mkdocs.yml
            mike set-default --push latest --config-file=docs/mkdocs.yml
          fi

