name: Security Workflow

on:
  push:
    branches: [main, feat/*, docs/*, fix/*, break/*, tests/*]
  pull_request:
    branches: [main, feat/*, docs/*, fix/*, break/*, tests/*]

jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...